### ISSUE TITLE
Push new NO lessons to curriculum repos

### ISSUE THREAD

**Issue by arve0** [RaspberryPiFoundation/lesson_format#140]
Hi!
Here in in Norway, we have deviated a bit from `lesson_format` and made our own [builder](/arve0/codeclub_lesson_builder) which is a bit more flexible for our needs. Also, we have created some new lessons and are in the works of creating more.

As the format has changed a bit (we've excluded things we do not need, in specific: some YAML properties and the manifest), I'm looking into creating a little sed-script which will add back these things so the lessons can be available on projects.codeclubworld.org.

When this script is done, will you want to have the new (norwegian only) lessons pushed also? I guess these lessons will be hard to translate to English, unless someone here steps up for the task.

**Comment by CodeClubRik** [comment]
Hi @arve0 - sorry for the huge delay in replying.

Yes, it'd be great to have the new lessons pushed as well. I'm currently in the process of separating out 'volunteer contributed projects' into their own manifest, so that they are separate to our 'core' curriculum.

Would it be possible for you to do something similar for these new projects?

Thanks,
Rik.

**Comment by arve0** [comment]
No worries, haven't had time yet anyhow. A contribution section would be
quite easy to fix. I'll look into the manifest files when I have some time
to look at this. Thanks :-)

**Comment by andylolz** [comment]
Renamed – did I get that right, @arve0?

**Comment by arve0** [comment]
Sounds right. Might want to move over to the right place, if the curriculum
repo are better suited.

**Comment by andylolz** [comment]
I’ll leave that to you! I’m not sure which repo :)
