### ISSUE TITLE
Ability to add “Test Your Project” within a step

### ISSUE THREAD

**Issue by rikcross** [RaspberryPiFoundation/lesson_format#142]
`##Test you project {.flag}`

So far I've been leaving these out of new projects, as they can only be placed at the end of a section. However, I've been encouraging children to test most new code as it's written, and so it'd be nice to include test points within a step, as well as at the end.

Is this possible? (@andylolz I know you mentioned that it might be this way by design, but it seems odd to have end-of-step test points in a green box but not those within a step.)

**Comment by andylolz** [comment]
You’re absolutely right! I _did_ say that, and I think I was completely wrong!

You really can’t “test your project” too much, so restricting where you can add that directive is not good.

Would you want these “Test your project” directives to look exactly as they do now?

**Comment by CodeClubRik** [comment]
i'm not sure you're _wrong_... it's also that the steps are quite long also, so need lots of test-points!

I think the test points look look great as they are!

**Comment by andylolz** [comment]
Kk – Cool :) But we agree that test points are good!

Right… Just having a go at this. So, here’s a test block inside a checklist item:

![screen shot 2015-02-06 at 17 36 55](https://cloud.githubusercontent.com/assets/464193/6084188/d05dce48-ae26-11e4-9114-c31fef645b7a.png)

I suspect this _isn’t_ what we’re after… Because having a test being part of a checklist item seems a bit weird. Checking the checklist item illustrates the weirdness:

![screen shot 2015-02-06 at 17 39 31](https://cloud.githubusercontent.com/assets/464193/6084276/737978c0-ae27-11e4-9482-66921a8310e0.png)

I wonder if it’s possible to split activity checklists up a bit? You can have multiple checklists within a step. But perhaps it’s desirable to only show the “Activity checklist” header on the first one? e.g.

![screen shot 2015-02-06 at 17 49 26](https://cloud.githubusercontent.com/assets/464193/6084398/91eb93e6-ae28-11e4-9cba-ae185bd0b931.png)

I guess the spacing needs working out a bit, but I think that last example could work. Wdyt?

**Comment by CodeClubRik** [comment]
I agree, that last example looks great. :+1:
