### ISSUE TITLE
Links to scratchcards/useful resources on each project page

### ISSUE THREAD

**Issue by andylolz** [RaspberryPiFoundation/lesson_format#161]
I find my club members sometimes need reminding of stuff like this:

![space-xy](https://cloud.githubusercontent.com/assets/464193/7747565/8f1eabd0-ffb3-11e4-893c-db741de0589a.png)

It’d be handy to define a set of useful links (to relevant scratchcards, and generally handy resources like this) in the project frontmatter, and then show these links on the project page.

**Comment by CodeClubRik** [comment]
New Scratch cards are on my to do list. I wonder whether it's worth creating a list of useful card topics first, so that I can write them up as new cards? We could then link to them as you suggest. It'd also mean we don't have to cross-link to other projects (for example, "forgotten what a variable is? go to the balloons project", which involves sifting through the entire project to find the relevant bit).

Suggestions for Scratch cards, based on the things I get asked a lot:

Costumes;
Sounds;
Score (variables);
Timers (variables / loops);
Sprites throwing objects (cloning);
Player movement -- platform (events/coordinates);
Player movement -- overhead (events/loops/decisions).


It might be nice to focus on 'things to make' rather than just the underlying concepts, so for example I've put coordinates in a 'player movement' card. What do you think?

**Comment by andylolz** [comment]
This sounds great! Glad you’ve been thinking about this.

> It might be nice to focus on 'things to make' rather than just the underlying concepts, so for example I've put coordinates in a 'player movement' card. What do you think?

Yeah definitely, that’s much better.

Tricky to remember other examples! I’ll have a think. It’s a good question to throw out to the Code Club volunteer community.

**Comment by martinpeck** [comment]
A couple of common requests I get are:

- Sprites shooting things (you've already got this)
- Platform games and gravity (allowing sprites to jump under gravity and fall off of platforms)
- Collision Detection (allowing sprites to hit walls, but not get "stuck" to them)

I wrote this little game to play with the last two on this list (platforms, gravity, collision etc): https://scratch.mit.edu/projects/53657486/

I wrote this game to play with shooting, moving, clones: https://scratch.mit.edu/projects/54918048/

**Comment by CodeClubRik** [comment]
Cheers @martinpeck

**Comment by martinpeck** [comment]
On, the other one I get a lot is how to retro-fit a "start/intro" screen, and how to add a "game over/score" screen. I end up teaching the kids that it's bad to wire up things to "when green flag clicked". Instead, they should have messages for "intro", "game start", "game over" and write up everything to those message, and make the green flash broadcast an event.

I'm not sure if that's something that could fit on a card, but it's a pattern that I end up showing kids.

**Comment by CodeClubRik** [comment]
That's the aim of the 'Brain Game' project. It's a really simple game but with a start screen and start button.
