### ISSUE TITLE
Right-to-left formatting bugs

### ISSUE THREAD

**Issue by rikcross** [RaspberryPiFoundation/lesson_format#186]
I think @andylolz mentioned previously that the rtl support was only tested for PDFs. I've added a couple of Hebrew projects, and the screenshot below shows a few formatting problems (mainly header/footer related).

![screen shot 2016-03-07 at 15 53 08](https://cloud.githubusercontent.com/assets/7372432/13630189/f2f1e5ec-e5d5-11e5-8843-ee87684b5b17.png)

**Comment by martinpeck** [comment]
FYI this is unlikely to get fixed because of #168

**Comment by andylolz** [comment]
Adding translations to the he-IL language file will probably help a bit:
https://github.com/CodeClub/lesson_format/blob/46e5128b/assets/languages/he-IL.language#L6-L8

Otherwise, you might possibly be able to add `rtl: true` to the frontmatter of project files, and remove it from the he-IL language file. Then the menus (which are currently largely in English) will at least remain left-to-right.

NB I haven’t tried either of these things – they’re just guesses. If it’s likely a PR will be accepted on this, I will take a look.

**Comment by rikcross** [comment]
Hi Andy, we have volunteers writing projects in rtl languages at present, and so it might complicate things to ask them to add extra data to the frontmatter.

**Comment by andylolz** [comment]
> it might complicate things to ask them to add extra data to the frontmatter

Yeah, fair enough. Well, this _might_ help:

> Adding translations to the he-IL language file will probably help a bit:
> https://github.com/CodeClub/lesson_format/blob/46e5128b/assets/languages/he-IL.language#L6-L8

Otherwise, the fix would involve changes to lesson_format.

**Comment by rikcross** [comment]
@freyjaodds and I also spotted that the checkboxes are on the wrong side.

![screen shot 2016-03-10 at 09 49 03](https://cloud.githubusercontent.com/assets/7372432/13665668/86dc9386-e6a5-11e5-9a61-171992579053.png)
